### ISSUE TITLE
Is it like CUTS/CUtopia?

### ISSUE THREAD

**Issue by isaackhlam** [AnsonCheng03/CUHK-Planner#1]
What is difference?

**Comment by AnsonCheng03** [comment]
This is not a issue, and the app is not for creating schedules.

**Comment by isaackhlam** [comment]
what is the repo for

**Comment by AnsonCheng03** [comment]
Will have first beta soon~

**Comment by isaackhlam** [comment]
Could u give a brief intro?

**Comment by AnsonCheng03** [comment]
An advance version of CU BUS Web. Combining the school bus estimate arrival time with your schedule and your location. additionally giving the restaurant besides you.

Timetable planning, course waitlist notifications, 外賣夾錢, view how crowd is the restaurant or bus, and course comment will be added if I am free and if there are plenty of active users

**Comment by AnsonCheng03** [comment]
It might be available later.
